#!/bin/bash

export PATH=$PATH:$HOME/.cargo/bin

cd "$(dirname "$0")"

function run {
  sleep 0.1
  echo Formatting: $file
  rustfmt --config-path rustfmt.toml "$file"
  echo $?
}

#inotifywait -m -q -e create,close_write,moved_to .

inotifywait -m -r -e create,close_write,moved_to --format '%w%f' . | while read file
do
  if [[ "$file" == *.rs ]]; then
    run "$file"
  fi
done
