// Class generated by ritual.
// See the template at "ritual/templates/c_lib/qt_signal_wrapper.h".
class {class_name} : public QObject {{
    Q_OBJECT
public:
    {class_name}() {{ }}

Q_SIGNALS:
    void emit_({method_args}){signal_impl}
}};
