pub const RUSTDOC: &str = "RITUAL_RUSTDOC";
pub const LIBRARY_PATH: &str = "RITUAL_LIBRARY_PATH";
pub const FRAMEWORK_PATH: &str = "RITUAL_FRAMEWORK_PATH";
pub const INCLUDE_PATH: &str = "RITUAL_INCLUDE_PATH";
pub const CLANG_SYSTEM_INCLUDE_PATH: &str = "CLANG_SYSTEM_INCLUDE_PATH";
